version: '3'
services:

  mydb:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiu
      - MYSQL_PASSWORD=kimaip
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
        - database:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
        - 8001:80
    volumes:
      - kimai:/opt/kimai
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
        - kimai_fpm

  kimai_fpm:
    image: kimai/kimai2:fpm-alpine-master
    environment:
        - APP_ENV=dev
        - TRUSTED_HOSTS=localhost
        - DATABASE_URL=mysql://kimaiu:kimaip@mydb/kimai
        - ADMINMAIL=kimai@example.com
        - ADMINPASS=changeme123
    volumes:
      - kimai:/opt/kimai
    restart: unless-stopped
    depends_on:
        - mydb

volumes:
    database:
    kimai: