apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: additional-{{ include "mysql.name" .}}-data
  labels:
    app.kubernetes.io/part-of: {{ .Values.metadata.applicationName }}
    app.kubernetes.io/name: additional-{{ include "mysql.name" .}}-data
spec:
  accessModes:
  - ReadWriteOnce
  {{ if .Values.default.storageClass }}
  storageClassName: {{ .Values.default.storageClass }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.mysql.pvc.data.size }}
