# example composer file for the fpm-alpine image
version: '3.5'
services:

  sql_db:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - database:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -pchangemeplease ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
        - 8001:80
    volumes:
      - kimai:/opt/kimai
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - kimai_fpm # because nginx will check if proxy upstream server is online
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai_fpm:
    # todo change to real image if ready
    image: test
    environment:
        - APP_ENV=prod
        - TRUSTED_HOSTS=localhost
        - DATABASE_URL=mysql://kimaiuser:kimaipassword@sql_db/kimai
        - ADMINMAIL=admin@kimai.local
        - ADMINPASS=changemeplease
    volumes:
      - kimai:/opt/kimai
    restart: unless-stopped
    depends_on:
      - sql_db
    healthcheck:
      test: wget --spider http://nginx || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

volumes:
    database:
    kimai: