version: '3.5'
services:

    kimai:
        volumes:
            - ./local.yaml:/opt/kimai/config/packages/local.yaml

    ldap:
        image: osixia/openldap:1.3.0
        ports:
            - 389:389
        environment:
            LDAP_ADMIN_PASSWORD: password123
        volumes:
            - ./ldap-seed.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
        command: --copy-service

    ldapadmin:
        image: dinkel/phpldapadmin
        links:
            - ldap:openldap
        ports:
            - 8003:80
        environment:
            LDAP_SERVER_HOST: ldap
            LDAP_SERVER_PORT: 389
        restart: always

