# example composer file for the fpm-alpine image
version: '3.5'
services:

    # Apache with sqlite, the dev/evaluate option
    kimai-apache-debian-sqlite-dev:
        image: kimai/kimai2:apache-debian-1.5-dev
        environment:
            - APP_ENV=dev
            - TRUSTED_HOSTS=localhost
            - ADMINMAIL=admin@kimai.local
            - ADMINPASS=changemeplease
        volumes:
            - /opt/kimai/var
        ports:
            - 8001:8001
        restart: unless-stopped
        healthcheck:
            test: wget --spider http://nginx || exit 1
            interval: 20s
            start_period: 10s
            timeout: 10s
            retries: 3

    # Apache with sqlite, the prod option
    kimai-apache-debian-sqlite-prod:
        image: kimai/kimai2:apache-debian-1.5-prod
        environment:
            - APP_ENV=prod
            - TRUSTED_HOSTS=localhost
            - ADMINMAIL=admin@kimai.local
            - ADMINPASS=changemeplease
        volumes:
            - /opt/kimai/var
        ports:
            - 8002:8001
        restart: unless-stopped
        healthcheck:
            test: wget --spider http://nginx || exit 1
            interval: 20s
            start_period: 10s
            timeout: 10s
            retries: 3

    # Apache with mysql, the dev/evaluate option
    kimai-apache-debian-mysql-dev:
        image: kimai/kimai2:apache-debian-1.5-dev
        environment:
            - APP_ENV=dev
            - TRUSTED_HOSTS=localhost
            - ADMINMAIL=admin@kimai.local
            - DATABASE_URL=mysql://kimaiuser:kimaipassword@kimai-apache-debian-mysql-dev-db/kimai
            - ADMINPASS=changemeplease
        volumes:
            - /opt/kimai/var
        ports:
            - 8003:8001
        restart: unless-stopped
        depends_on:
            - kimai-apache-debian-mysql-dev-db
        healthcheck:
            test: wget --spider http://nginx || exit 1
            interval: 20s
            start_period: 10s
            timeout: 10s
            retries: 3

    kimai-apache-debian-mysql-dev-db:
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=kimai
            - MYSQL_USER=kimaiuser
            - MYSQL_PASSWORD=kimaipassword
            - MYSQL_ROOT_PASSWORD=changemeplease
        volumes:
            - /var/lib/mysql
        command: --default-storage-engine innodb 
        restart: unless-stopped
        healthcheck:
            test: mysqladmin -pchangemeplease ping -h localhost
            interval: 20s
            start_period: 10s
            timeout: 10s
            retries: 3
            
            #nginx:
            #image: nginx:alpine
            #ports:
            #- 8001:80
            #volumes:
            #- kimai_source:/opt/kimai
            #- ./nginx_site.conf:/etc/nginx/conf.d/default.conf
            #restart: unless-stopped
            #depends_on:
            #- kimai_fpm # because nginx will check if proxy upstream server is online
            #healthcheck:
            #test:  wget --spider http://nginx/health || exit 1
            #interval: 20s
            #start_period: 10s
            #timeout: 10s
            #retries: 3
            #
            #kimai_fpm:
            ## todo change to real image if ready
            #image: kimai
            #environment:
            #- APP_ENV=prod
            #- TRUSTED_HOSTS=localhost
            #- DATABASE_URL=mysql://kimaiuser:kimaipassword@sql_db/kimai
            #- ADMINMAIL=admin@kimai.local
            #- ADMINPASS=changemeplease
            #volumes:
            #- kimai_source:/opt/kimai
            #- kimai_var:/opt/kimai/var
            #restart: unless-stopped
            #depends_on:
            #- sql_db
            #healthcheck:
            #test: wget --spider http://nginx || exit 1
            #interval: 20s
            #start_period: 10s
            #timeout: 10s
            #retries: 3
            #
            #volumes:
            #database:
            #kimai_source:
            #kimai_var:
