apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core-{{ include "kimai.name" .}}-var
  labels:
    app.kubernetes.io/part-of: {{ .Values.metadata.applicationName }}
    app.kubernetes.io/name: core-{{ include "kimai.name" . }}-var
spec:
  accessModes:
  - ReadWriteOnce
  {{ if .Values.default.storageClass }}
  storageClassName: {{ .Values.default.storageClass }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.kimai.pvc.var.size }}
