apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kimai2.name" .}}-data
  labels:
    app.kubernetes.io/part-of: {{ include "kimai2.name" . }}
    app.kubernetes.io/name: {{ include "kimai2.name" . }}-data
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
      {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- include "common.storage.class" (dict "persistence" .Values.persistence "global" .Values.global) | nindent 2 }}
