apiVersion: v1
kind: Service
metadata:
  name: additional-{{ include "mysql.name" .}}
  labels:
    app.kubernetes.io/part-of: {{ .Values.metadata.applicationName }}
    app.kubernetes.io/name: additional-{{ include "mysql.name" .}}
    app.kubernetes.io/component: additional-{{ include "mysql.name" .}}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      targetPort: mysql
      name: mysql
  selector:
    app.kubernetes.io/part-of: {{ .Values.metadata.applicationName }}
    app.kubernetes.io/name: additional-{{ include "mysql.name" .}}
    app.kubernetes.io/component: additional-{{ include "mysql.name" .}}
