apiVersion: v1
kind: Service
metadata:
  name: core-{{ include "kimai.name" .}}
  labels:
    app.kubernetes.io/part-of: {{ .Values.metadata.applicationName }}
    app.kubernetes.io/name: core-{{ include "kimai.name" .}}
    app.kubernetes.io/component: core-{{ include "kimai.name" .}}
spec:
  type: ClusterIP
  ports:
    - port: 8001
      protocol: TCP
      targetPort: kimai-http
      name: kimai-http
  selector:
    app.kubernetes.io/part-of: {{ .Values.metadata.applicationName }}
    app.kubernetes.io/name: core-{{ include "kimai.name" .}}
    app.kubernetes.io/component: core-{{ include "kimai.name" .}}
