version: '3'
services:

  # NB This file tears up a set of testing/sample containers.
  # They connect to mysql as root, don't do this in production.
  # They are also transient in that the mysql db does not persist.

  mydb:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d
    command: --default-storage-engine innodb
    restart: always

  postfix:
    image: catatnight/postfix
    environment:
      maildomain: neontribe.co.uk
      smtp_user: kimai:kimai
    restart: unless-stopped
    restart: always

  nginx:
    image: nginx:alpine
    ports:
        - 8141
        - 8142
        - 8143
        - 8144
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf
      - ./kimai:/opt/kimai
    restart: unless-stopped
    depends_on:
      - fpm-debian-1.4
      - fpm-alpine-1.4
      - fpm-debian-1.4.1
      - fpm-alpine-1.4.1
          
  apache-debian-1.4.1:
    image: kimai/kimai2:apache-debian-master
    environment:
        - APP_ENV=prod
        - DATABASE_URL=mysql://root:changeme@mydb/kimai_ad_141
        - ADMINMAIL=kimai@example.com
        - ADMINPASS=changeme123
    depends_on:
        - mydb
    ports:
        - 8001
    restart: always

  apache-debian-1.4:
    image: kimai/kimai2:apache-debian-master
    environment:
        - APP_ENV=prod
        - DATABASE_URL=mysql://root:changeme@mydb/kimai_ad_14
        - ADMINMAIL=kimai@example.com
        - ADMINPASS=changeme123
    depends_on:
        - mydb
    ports:
        - 8001
    restart: always
 
  fpm-debian-1.4:
    image: kimai/kimai2:fpm-debian-1.4.1
    environment:
        - APP_ENV=prod
        - DATABASE_URL=mysql://root:changeme@mydb/kimai_fd_14
        - ADMINMAIL=kimai@example.com
        - ADMINPASS=changeme123
        - TRUSTED_HOSTS=localhost
    depends_on:
        - mydb
    restart: always

  fpm-alpine-1.4:
    image: kimai/kimai2:fpm-debian-1.4.1
    environment:
        - APP_ENV=prod
        - DATABASE_URL=mysql://root:changeme@mydb/kimai_fa_14
        - ADMINMAIL=kimai@example.com
        - ADMINPASS=changeme123
        - TRUSTED_HOSTS=localhost
    depends_on:
        - mydb
    restart: always

  fpm-debian-1.4.1:
    image: kimai/kimai2:fpm-debian-1.4.1
    environment:
        - APP_ENV=prod
        - DATABASE_URL=mysql://root:changeme@mydb/kimai_fd_141
        - ADMINMAIL=kimai@example.com
        - ADMINPASS=changeme123
        - TRUSTED_HOSTS=localhost
    depends_on:
        - mydb
    restart: always

  fpm-alpine-1.4.1:
    image: kimai/kimai2:fpm-debian-1.4.1
    environment:
        - APP_ENV=prod
        - DATABASE_URL=mysql://root:changeme@mydb/kimai_fq_141
        - ADMINMAIL=kimai@example.com
        - ADMINPASS=changeme123
        - TRUSTED_HOSTS=localhost
    depends_on:
        - mydb
    restart: always
