name: Build main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t kimai/kimai2:fpm-master-dev --build-arg KIMAI=master --build-arg BASE=fpm --build-arg TZ=${TIMEZONE} --target=dev .

