name: Build and push
on: [push]
    #push:
    #branches:
    #- master
    #tags:
    #- v*

jobs:
    build:
        name: Build kimai docker, ${{ matrix.stage }} and ${{ matrix.base }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                stage: [dev, prod]
                base: [apache-debian, fpm-alpine]

        steps:
          - name: Checkout master
            uses: actions/checkout@v2

          - name: Build and publish image
            env:
                DOCKER_BUILDKIT: 1
                KIMAI: $(echo "${github.ref}" | sed -e 's,.*/\(.*\),\1,')
            shell: bash
            run: |
                docker build -t kimai/kimai2:${matrix.base}-${KIMAI}-${matrix.stage} --build-arg KIMAI=${KIMAI} --build-arg BASE=${matrix.base} --build-arg TZ=Europe/London --target=${matrix.stage} .

                # dockerHubUser: YOUR_USER_HERE
                # dockerHubPassword: YOUR_PASSWORD_HERE
